adventure/urls.py
from django.contrib import admin
from django.urls import include, path

from adventure import views

urlpatterns = [
    path('', views.start, name='start'),
    path('<str:name>', views.station, name='station'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('uploader/', include('uploader.urls')),
    path('todo/', include('todo.urls')),
    path('todolist/', include('todolist.urls')),
    path('adventure/', include('adventure.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('update/<int:item_id>/', views.update, name='update'),
    path('delete/<int:item_id>/', views.delete, name='delete'),
    path('done/<int:item_id>/', views.done, name='done'),
]

adventure/models.py
from django.db import models

# Create your models here.

class Station(models.Model):
    '''
    Eine Station im Textadventure. Der Name ist eine sprechende ID,
    muss also eindeutig (unique) sein.
    '''
    name = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='', max_length=200, null=True)
    def __str__(self):
        return self.name

class Choice(models.Model):
    '''
    Eine Auswahloption. Neben dem Text zur Beschreibung enthält Sie auch den
    Verweis auf die nächste Station.
    '''
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    next_station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="incoming_set")

    def __str__(self):
        return f"{self.text}: {self.next_station.name}"



class Player(models.Model):
    name = models.CharField(max_length=200, null = False)
    experience = models.IntegerField(default=0)
    health = models.IntegerField(default=100)
    def __str__(self):
        return self.name

class Item(models.Model):
    item = models.CharField(max_length=200)
    image = models.ImageField(upload_to='item', max_length=200, null=True)
    def __str__(self):
        return self.item

class Inventory_entry(models.Model):
    # many-to-many relation
    player = models.ForeignKey(to=Player, on_delete=models.CASCADE)
    item = models.ForeignKey(to=Item, on_delete=models.CASCADE)

adventure/views.py
from django.shortcuts import render, get_object_or_404


# Create your views here.
from adventure import models

def start(request, name='start'):
    station = get_object_or_404(models.Station, pk=1)
    return render(request, "adventure/station.html", {"station": station})

def station(request, name="station"):
    '''
    Hier wird die passende Station geholt und ausgegeben.
    Wird kein Name übergeben, dann wird die Station 'start' geholt.
    '''
    station = get_object_or_404(models.Station, name=name)
    return render(request, "adventure/station.html", {"station": station})

adventure/templates/adventure/base.html
{%  load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static '/css/rpgui.min.css' %}" rel="stylesheet" type="text/css" >
    <script src="{% static '/js/rpgui.min.js' %}"></script>
    <style>
        .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
    </style>
</head>
<body>
    <div class="rpgui-content rpgui-cursor-default" style="overflow-y:scroll;">

        <div class="container">
            <div id="main"></div>
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

adventure/templates/adventure/index.html
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{station.title}}</h5>
      <p class="card-text">{{station.text}}</p>
      {% for choice in station.choice_set.all %}
        <a href="{{choice.next_station.name}}" class="btn btn-primary">{{choice.text}}</a>
      {% endfor %}
    </div>
  </div>
</div>

adventure/templates/adventure/station.html
{% extends 'adventure/base.html' %}
{% load static %}

{%  block content %}
<div class="inner rpgui-container framed" style="position:relative" >
  <div class="">
      <header><h1 class="" style="font-size:250%">{{station.title}}</h1></header>
        <hr class="golden">
        <div class="rpgui-container framed-grey">
            <img src="/media/{{ station.image }}" class="center" style="max-width: 1024px; max-height: 100%; object-fit: contain; "/>
        </div>
        <div class="rpgui-container framed-grey">
            <p class="">{{station.text}}</p>
        </div>
        <div class="rpgui-center">
        {% for choice in station.choice_set.all %}
            <button onclick="window.location.href='{{choice.next_station.name}}'" class="rpgui-button">{{choice.text}}</button>
        {% endfor %}
        </div>

    </div>
  </div>
{%  endblock %}