mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('uploader/', include('uploader.urls')),
    path('todo/', include('todo.urls')),
    path('todolist/', include('todolist.urls')),
    path('adventure/', include('adventure.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('update/<int:item_id>/', views.update, name='update'),
    path('delete/<int:item_id>/', views.delete, name='delete'),
    path('done/<int:item_id>/', views.done, name='done'),
]

uploader/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from uploader import views

app_name = 'uploader'
urlpatterns = [
    path('', views.index, name='index'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploader/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Image(models.Model):
    created_at = models.DateTimeField('date created', auto_now_add=True)
    image_file = models.ImageField(upload_to=settings.MEDIA_ROOT[1:], blank=False) #

uploader/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

uploader/views.py
from django.shortcuts import render

# Create your views here.
from .models import Image
from .forms import UploadFileForm

def index(request):
    all_images = Image.objects.all()

    context = {'images': all_images}

    if request.method == 'POST':
        '''
        form = UploadFileForm(request.POST, request.FILES)
        
        if form.is_valid:
            print(request.FILES)
            image = Image(image_file=request.FILES['file'])
            image.save()
        '''

        print('Image:', request.FILES['image'])
        image = Image(image_file=request.FILES['image'])
        image.save()

    return render(request, 'uploader/index.html', context=context)

uploader/templates/uploader/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<h1>Image Upload</h1>
<form method="post" enctype="multipart/form-data" action="{% url 'uploader:index' %}">
    {% csrf_token %}
    <input type="file" name="image" id="image" />
    <button>Submit</button>
</form>
<hr />
<h2> All Images</h2>
{% for image in images %}
    <div>
        <p>
            {{ image.created_at }}
        </p>
        <p>
            <img src="{{ image.image_file.url }}" alt="{{ image.created_at }}" width="100px" height="auto"/>
        </p>
    </div>
{% endfor %}
</body>
</html>